# Generated by Django 3.2.7 on 2021-09-14 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('briefing', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='media')),
                ('dataCriacao', models.DateTimeField(verbose_name='Data da Criacao')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
