# Generated by Django 5.2.7 on 2025-10-21 07:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'Title is required.', 'max_length': 'Title must be at most 70 characters.', 'null': 'Title cannot be null.'}, max_length=70, validators=[django.core.validators.MinLengthValidator(5, message='Title must be at least 5 characters.'), django.core.validators.MaxLengthValidator(70, message='Title must be at most 70 characters.')], verbose_name='Title')),
                ('briefing', models.CharField(error_messages={'blank': 'Briefing is required.', 'max_length': 'Briefing must be at most 100 characters.', 'null': 'Briefing cannot be null.'}, max_length=100, validators=[django.core.validators.MinLengthValidator(5, message='Briefing must be at least 5 characters.'), django.core.validators.MaxLengthValidator(100, message='Briefing must be at most 100 characters.')], verbose_name='Briefing')),
                ('text', models.TextField(error_messages={'blank': 'Text is required.', 'null': 'Text cannot be null.'}, validators=[django.core.validators.MinLengthValidator(100, message='Text must be at least 100 characters.'), django.core.validators.MaxLengthValidator(3000, message='Text must be at most 3000 characters.')], verbose_name='Text')),
                ('picture', models.ImageField(default='posts/noimage.png', error_messages={'blank': 'Picture is empty.', 'invalid': 'Invalid picture file.', 'null': 'Picture is null.'}, upload_to='posts/', verbose_name='Picture')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, error_messages={'blank': 'Creation date is required.', 'invalid': 'Invalid datetime format for creation date.', 'null': 'Creation date cannot be null.'}, verbose_name='Create At')),
                ('update_at', models.DateTimeField(blank=True, error_messages={'invalid': 'Invalid datetime format for update date.'}, null=True, verbose_name='Update At')),
                ('author', models.ForeignKey(error_messages={'invalid': 'Invalid author.', 'null': 'Author is required.'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
            },
        ),
    ]
